# Generated by Django 5.0.3 on 2024-04-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_postmodel_liked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="likenumber",
            field=models.IntegerField(default=0),
        ),
    ]
